//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSWeb.AccesoDatos.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StoredProcedure {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StoredProcedure() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POSWeb.AccesoDatos.Resources.StoredProcedure", typeof(StoredProcedure).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paCambiarContrasena.
        /// </summary>
        public static string CambiarContrasena {
            get {
                return ResourceManager.GetString("CambiarContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paEliminarAlerta.
        /// </summary>
        public static string EliminarAlerta {
            get {
                return ResourceManager.GetString("EliminarAlerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paEliminarAlertaEntidad.
        /// </summary>
        public static string EliminarAlertaEntidad {
            get {
                return ResourceManager.GetString("EliminarAlertaEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paEliminarCuentaEmail.
        /// </summary>
        public static string EliminarCuentaEmail {
            get {
                return ResourceManager.GetString("EliminarCuentaEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paEliminarModulo.
        /// </summary>
        public static string EliminarModulo {
            get {
                return ResourceManager.GetString("EliminarModulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paEliminarPerfil.
        /// </summary>
        public static string EliminarPerfil {
            get {
                return ResourceManager.GetString("EliminarPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paEliminarProducto.
        /// </summary>
        public static string EliminarProducto {
            get {
                return ResourceManager.GetString("EliminarProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paEliminarRol.
        /// </summary>
        public static string EliminarRol {
            get {
                return ResourceManager.GetString("EliminarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paEliminarSesion.
        /// </summary>
        public static string EliminarSesion {
            get {
                return ResourceManager.GetString("EliminarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paEliminarUsuario.
        /// </summary>
        public static string EliminarUsuario {
            get {
                return ResourceManager.GetString("EliminarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paInsertarAlerta.
        /// </summary>
        public static string InsertarAlerta {
            get {
                return ResourceManager.GetString("InsertarAlerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paInsertarAlertaEntidad.
        /// </summary>
        public static string InsertarAlertaEntidad {
            get {
                return ResourceManager.GetString("InsertarAlertaEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paInsertarAutorizacion.
        /// </summary>
        public static string InsertarAutorizacion {
            get {
                return ResourceManager.GetString("InsertarAutorizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paInsertarAutorizacionDetalle.
        /// </summary>
        public static string InsertarAutorizacionDetalle {
            get {
                return ResourceManager.GetString("InsertarAutorizacionDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paInsertarCuentaEmail.
        /// </summary>
        public static string InsertarCuentaEmail {
            get {
                return ResourceManager.GetString("InsertarCuentaEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paInsertarModulo.
        /// </summary>
        public static string InsertarModulo {
            get {
                return ResourceManager.GetString("InsertarModulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paInsertarPerfil.
        /// </summary>
        public static string InsertarPerfil {
            get {
                return ResourceManager.GetString("InsertarPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paInsertarProducto.
        /// </summary>
        public static string InsertarProducto {
            get {
                return ResourceManager.GetString("InsertarProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paInsertarRol.
        /// </summary>
        public static string InsertarRol {
            get {
                return ResourceManager.GetString("InsertarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paInsertarSesion.
        /// </summary>
        public static string InsertarSesion {
            get {
                return ResourceManager.GetString("InsertarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paInsertarUsuario.
        /// </summary>
        public static string InsertarUsuario {
            get {
                return ResourceManager.GetString("InsertarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paModificarAlerta.
        /// </summary>
        public static string ModificarAlerta {
            get {
                return ResourceManager.GetString("ModificarAlerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paModificarAlertaEntidad.
        /// </summary>
        public static string ModificarAlertaEntidad {
            get {
                return ResourceManager.GetString("ModificarAlertaEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paModificarCatalogo.
        /// </summary>
        public static string ModificarCatalogo {
            get {
                return ResourceManager.GetString("ModificarCatalogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paModificarCuentaEmail.
        /// </summary>
        public static string ModificarCuentaEmail {
            get {
                return ResourceManager.GetString("ModificarCuentaEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paModificarModulo.
        /// </summary>
        public static string ModificarModulo {
            get {
                return ResourceManager.GetString("ModificarModulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paModificarPerfil.
        /// </summary>
        public static string ModificarPerfil {
            get {
                return ResourceManager.GetString("ModificarPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paModificarProducto.
        /// </summary>
        public static string ModificarProducto {
            get {
                return ResourceManager.GetString("ModificarProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paModificarRol.
        /// </summary>
        public static string ModificarRol {
            get {
                return ResourceManager.GetString("ModificarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paModificarSesion.
        /// </summary>
        public static string ModificarSesion {
            get {
                return ResourceManager.GetString("ModificarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paModificarUsuario.
        /// </summary>
        public static string ModificarUsuario {
            get {
                return ResourceManager.GetString("ModificarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paObtenerAccion.
        /// </summary>
        public static string ObtenerAccion {
            get {
                return ResourceManager.GetString("ObtenerAccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paObtenerAccionesPerfil.
        /// </summary>
        public static string ObtenerAccionesPerfil {
            get {
                return ResourceManager.GetString("ObtenerAccionesPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paObtenerAlerta.
        /// </summary>
        public static string ObtenerAlerta {
            get {
                return ResourceManager.GetString("ObtenerAlerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paObtenerAlertaEntidad.
        /// </summary>
        public static string ObtenerAlertaEntidad {
            get {
                return ResourceManager.GetString("ObtenerAlertaEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paObtenerAlertaEntidadPag.
        /// </summary>
        public static string ObtenerAlertaEntidadPaginado {
            get {
                return ResourceManager.GetString("ObtenerAlertaEntidadPaginado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paObtenerAlertaPag.
        /// </summary>
        public static string ObtenerAlertaPaginado {
            get {
                return ResourceManager.GetString("ObtenerAlertaPaginado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paObtenerAutorizacion.
        /// </summary>
        public static string ObtenerAutorizacion {
            get {
                return ResourceManager.GetString("ObtenerAutorizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paObtenerAutorizacionDetalle.
        /// </summary>
        public static string ObtenerAutorizacionDetalle {
            get {
                return ResourceManager.GetString("ObtenerAutorizacionDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paObtenerAutorizacionDetallePaginado.
        /// </summary>
        public static string ObtenerAutorizacionDetallePaginado {
            get {
                return ResourceManager.GetString("ObtenerAutorizacionDetallePaginado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paObtenerAutorizacionPaginado.
        /// </summary>
        public static string ObtenerAutorizacionPaginado {
            get {
                return ResourceManager.GetString("ObtenerAutorizacionPaginado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paObtenerBitacora.
        /// </summary>
        public static string ObtenerBitacora {
            get {
                return ResourceManager.GetString("ObtenerBitacora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paObtenerBitacoraPaginado.
        /// </summary>
        public static string ObtenerBitacoraPaginado {
            get {
                return ResourceManager.GetString("ObtenerBitacoraPaginado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paObtenerCatalogo.
        /// </summary>
        public static string ObtenerCatalogo {
            get {
                return ResourceManager.GetString("ObtenerCatalogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paObtenerCatalogoPaginado.
        /// </summary>
        public static string ObtenerCatalogoPaginado {
            get {
                return ResourceManager.GetString("ObtenerCatalogoPaginado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paObtenerControlador.
        /// </summary>
        public static string ObtenerControlador {
            get {
                return ResourceManager.GetString("ObtenerControlador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paObtenerCuentaEmail.
        /// </summary>
        public static string ObtenerCuentaEmail {
            get {
                return ResourceManager.GetString("ObtenerCuentaEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paObtenerCuentaEmailPag.
        /// </summary>
        public static string ObtenerCuentaEmailPaginado {
            get {
                return ResourceManager.GetString("ObtenerCuentaEmailPaginado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paObtenerMenuUsuario.
        /// </summary>
        public static string ObtenerMenuUsuario {
            get {
                return ResourceManager.GetString("ObtenerMenuUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paObtenerModulo.
        /// </summary>
        public static string ObtenerModulo {
            get {
                return ResourceManager.GetString("ObtenerModulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paObtenerModuloPag.
        /// </summary>
        public static string ObtenerModuloPaginado {
            get {
                return ResourceManager.GetString("ObtenerModuloPaginado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paObtenerPais.
        /// </summary>
        public static string ObtenerPais {
            get {
                return ResourceManager.GetString("ObtenerPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paObtenerPerfil.
        /// </summary>
        public static string ObtenerPerfil {
            get {
                return ResourceManager.GetString("ObtenerPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paObtenerPerfilPag.
        /// </summary>
        public static string ObtenerPerfilPaginado {
            get {
                return ResourceManager.GetString("ObtenerPerfilPaginado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paObtenerPerfilPorRol.
        /// </summary>
        public static string ObtenerPerfilPorRol {
            get {
                return ResourceManager.GetString("ObtenerPerfilPorRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paObtenerProducto.
        /// </summary>
        public static string ObtenerProducto {
            get {
                return ResourceManager.GetString("ObtenerProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paObtenerProductoPag.
        /// </summary>
        public static string ObtenerProductoPaginado {
            get {
                return ResourceManager.GetString("ObtenerProductoPaginado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paObtenerRol.
        /// </summary>
        public static string ObtenerRol {
            get {
                return ResourceManager.GetString("ObtenerRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paObtenerRolPaginado.
        /// </summary>
        public static string ObtenerRolPaginado {
            get {
                return ResourceManager.GetString("ObtenerRolPaginado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paObtenerRolPorUsuario.
        /// </summary>
        public static string ObtenerRolPorUsuario {
            get {
                return ResourceManager.GetString("ObtenerRolPorUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paObtenerSesion.
        /// </summary>
        public static string ObtenerSesion {
            get {
                return ResourceManager.GetString("ObtenerSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paObtenerSesionPaginado.
        /// </summary>
        public static string ObtenerSesionPaginado {
            get {
                return ResourceManager.GetString("ObtenerSesionPaginado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paObtenerTipoIdentificacion.
        /// </summary>
        public static string ObtenerTipoIdentificacion {
            get {
                return ResourceManager.GetString("ObtenerTipoIdentificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paObtenerUsuario.
        /// </summary>
        public static string ObtenerUsuario {
            get {
                return ResourceManager.GetString("ObtenerUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paObtenerUsuarioPaginado.
        /// </summary>
        public static string ObtenerUsuarioPaginado {
            get {
                return ResourceManager.GetString("ObtenerUsuarioPaginado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paProcesarAutorizacion.
        /// </summary>
        public static string ProcesarAutorizacion {
            get {
                return ResourceManager.GetString("ProcesarAutorizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paValidarUsuarioLogin.
        /// </summary>
        public static string ValidarUsuarioLogin {
            get {
                return ResourceManager.GetString("ValidarUsuarioLogin", resourceCulture);
            }
        }
    }
}
