//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSWeb.Entidades.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Generales {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Generales() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POSWeb.Entidades.ResourceFiles.Generales", typeof(Generales).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar.
        /// </summary>
        public static string btnActualizar {
            get {
                return ResourceManager.GetString("btnActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar.
        /// </summary>
        public static string btnAgregarArchivos {
            get {
                return ResourceManager.GetString("btnAgregarArchivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicar.
        /// </summary>
        public static string btnAplicar {
            get {
                return ResourceManager.GetString("btnAplicar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprobar.
        /// </summary>
        public static string btnAprobar {
            get {
                return ResourceManager.GetString("btnAprobar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorizar.
        /// </summary>
        public static string btnAutorizar {
            get {
                return ResourceManager.GetString("btnAutorizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string btnCancelar {
            get {
                return ResourceManager.GetString("btnCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargar.
        /// </summary>
        public static string btnCargar {
            get {
                return ResourceManager.GetString("btnCargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar.
        /// </summary>
        public static string btnConsultar {
            get {
                return ResourceManager.GetString("btnConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear.
        /// </summary>
        public static string btnCrear {
            get {
                return ResourceManager.GetString("btnCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar.
        /// </summary>
        public static string btnDefinirRegla {
            get {
                return ResourceManager.GetString("btnDefinirRegla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string btnGuardar {
            get {
                return ResourceManager.GetString("btnGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechazar.
        /// </summary>
        public static string btnRechazar {
            get {
                return ResourceManager.GetString("btnRechazar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Volver.
        /// </summary>
        public static string btnVolver {
            get {
                return ResourceManager.GetString("btnVolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy.
        /// </summary>
        public static string FormatoFecha {
            get {
                return ResourceManager.GetString("FormatoFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa fa-pencil fa-2x.
        /// </summary>
        public static string IconoActualizar {
            get {
                return ResourceManager.GetString("IconoActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa fa-refresh.
        /// </summary>
        public static string IconoBtnActualizar {
            get {
                return ResourceManager.GetString("IconoBtnActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa fa-plus.
        /// </summary>
        public static string IconoBtnAgregar {
            get {
                return ResourceManager.GetString("IconoBtnAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa fa-thumbs-up fa-2x.
        /// </summary>
        public static string IconoBtnAprobar {
            get {
                return ResourceManager.GetString("IconoBtnAprobar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa fa-search.
        /// </summary>
        public static string IconoBtnConsultar {
            get {
                return ResourceManager.GetString("IconoBtnConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa fa-external-link.
        /// </summary>
        public static string IconoBtnConsultarReporte {
            get {
                return ResourceManager.GetString("IconoBtnConsultarReporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa fa-plus.
        /// </summary>
        public static string IconoBtnCrear {
            get {
                return ResourceManager.GetString("IconoBtnCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa fa-home fa-2x.
        /// </summary>
        public static string IconoBtnHome {
            get {
                return ResourceManager.GetString("IconoBtnHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa fa-thumbs-down fa-2x.
        /// </summary>
        public static string IconoBtnRechazar {
            get {
                return ResourceManager.GetString("IconoBtnRechazar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa fa-upload .
        /// </summary>
        public static string IconoBtnSubirArchivo {
            get {
                return ResourceManager.GetString("IconoBtnSubirArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa fa-reply.
        /// </summary>
        public static string IconoBtnVolver {
            get {
                return ResourceManager.GetString("IconoBtnVolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa fa-check-square-o.
        /// </summary>
        public static string IconoCheck {
            get {
                return ResourceManager.GetString("IconoCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa fa-bars .
        /// </summary>
        public static string IconoDefinirReglas {
            get {
                return ResourceManager.GetString("IconoDefinirReglas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa fa-bars fa-2x.
        /// </summary>
        public static string IconoDefinirReglasx2 {
            get {
                return ResourceManager.GetString("IconoDefinirReglasx2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa fa-times-circle fa-2x.
        /// </summary>
        public static string IconoEliminar {
            get {
                return ResourceManager.GetString("IconoEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa fa-times-circle.
        /// </summary>
        public static string IconoEliminarPequeño {
            get {
                return ResourceManager.GetString("IconoEliminarPequeño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa fa-envelope-o fa-2x.
        /// </summary>
        public static string IconoEmail {
            get {
                return ResourceManager.GetString("IconoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa fa-cog fa-2x.
        /// </summary>
        public static string IconoGestionar {
            get {
                return ResourceManager.GetString("IconoGestionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa fa-eye fa-2x.
        /// </summary>
        public static string IconoVer {
            get {
                return ResourceManager.GetString("IconoVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfiles.
        /// </summary>
        public static string lblPerfiles {
            get {
                return ResourceManager.GetString("lblPerfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrataciones.
        /// </summary>
        public static string TituloPestanna {
            get {
                return ResourceManager.GetString("TituloPestanna", resourceCulture);
            }
        }
    }
}
