//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSWeb.Entidades.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lblViews {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lblViews() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POSWeb.Entidades.ResourceFiles.lblViews", typeof(lblViews).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar.
        /// </summary>
        public static string Cambiar {
            get {
                return ResourceManager.GetString("Cambiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametro.
        /// </summary>
        public static string CodigoParametro {
            get {
                return ResourceManager.GetString("CodigoParametro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Usuario.
        /// </summary>
        public static string CodigoUsuario {
            get {
                return ResourceManager.GetString("CodigoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorizaciones Realizadas.
        /// </summary>
        public static string ConteoAutorizacion {
            get {
                return ResourceManager.GetString("ConteoAutorizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string Contrasena {
            get {
                return ResourceManager.GetString("Contrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo Electrónico.
        /// </summary>
        public static string CorreoElectronico {
            get {
                return ResourceManager.GetString("CorreoElectronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string Estado {
            get {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Autorización.
        /// </summary>
        public static string FechaAutorizacion {
            get {
                return ResourceManager.GetString("FechaAutorizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Expiración Contraseña.
        /// </summary>
        public static string FechaExpiracionClave {
            get {
                return ResourceManager.GetString("FechaExpiracionClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Hasta.
        /// </summary>
        public static string FechaFinal {
            get {
                return ResourceManager.GetString("FechaFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Desde.
        /// </summary>
        public static string FechaInicio {
            get {
                return ResourceManager.GetString("FechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Registro.
        /// </summary>
        public static string FechaRegistro {
            get {
                return ResourceManager.GetString("FechaRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorización.
        /// </summary>
        public static string IdAutorizacion {
            get {
                return ResourceManager.GetString("IdAutorizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorización Detalle.
        /// </summary>
        public static string IdAutorizacionDetalle {
            get {
                return ResourceManager.GetString("IdAutorizacionDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificación.
        /// </summary>
        public static string Identificacion {
            get {
                return ResourceManager.GetString("Identificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        public static string IdPais {
            get {
                return ResourceManager.GetString("IdPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador.
        /// </summary>
        public static string IdRecurso {
            get {
                return ResourceManager.GetString("IdRecurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Identificación.
        /// </summary>
        public static string IdTipoIdentificacion {
            get {
                return ResourceManager.GetString("IdTipoIdentificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intentos Fallidos.
        /// </summary>
        public static string IntentosFallidos {
            get {
                return ResourceManager.GetString("IntentosFallidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string lblRoles {
            get {
                return ResourceManager.GetString("lblRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje Registro.
        /// </summary>
        public static string MensajeRegistro {
            get {
                return ResourceManager.GetString("MensajeRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje Técnico.
        /// </summary>
        public static string MensajeTecnico {
            get {
                return ResourceManager.GetString("MensajeTecnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No exiten datos registrados.
        /// </summary>
        public static string noHayDatos {
            get {
                return ResourceManager.GetString("noHayDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Token Admin!.
        /// </summary>
        public static string nombreSitio {
            get {
                return ResourceManager.GetString("nombreSitio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerta.
        /// </summary>
        public static string objAlertaEntidad {
            get {
                return ResourceManager.GetString("objAlertaEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorización.
        /// </summary>
        public static string objAutorizacion {
            get {
                return ResourceManager.GetString("objAutorizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitácora.
        /// </summary>
        public static string objBitacora {
            get {
                return ResourceManager.GetString("objBitacora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar Constraseña.
        /// </summary>
        public static string objCambiarClave {
            get {
                return ResourceManager.GetString("objCambiarClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canal.
        /// </summary>
        public static string objCanal {
            get {
                return ResourceManager.GetString("objCanal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogo.
        /// </summary>
        public static string objCatalogo {
            get {
                return ResourceManager.GetString("objCatalogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta Email.
        /// </summary>
        public static string objCuentaEmail {
            get {
                return ResourceManager.GetString("objCuentaEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidad Bancaria.
        /// </summary>
        public static string objEntidadBancaria {
            get {
                return ResourceManager.GetString("objEntidadBancaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partida Presupuestal.
        /// </summary>
        public static string objPartidaPresupuestal {
            get {
                return ResourceManager.GetString("objPartidaPresupuestal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alertas.
        /// </summary>
        public static string objPluralAlertaEntidad {
            get {
                return ResourceManager.GetString("objPluralAlertaEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorizaciones.
        /// </summary>
        public static string objPluralAutorizacion {
            get {
                return ResourceManager.GetString("objPluralAutorizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitacoras.
        /// </summary>
        public static string objPluralBitacora {
            get {
                return ResourceManager.GetString("objPluralBitacora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canales.
        /// </summary>
        public static string objPluralCanal {
            get {
                return ResourceManager.GetString("objPluralCanal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogos.
        /// </summary>
        public static string objPluralCatalogo {
            get {
                return ResourceManager.GetString("objPluralCatalogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuentas Email.
        /// </summary>
        public static string objPluralCuentaEmail {
            get {
                return ResourceManager.GetString("objPluralCuentaEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidades Bancarias.
        /// </summary>
        public static string objPluralEntidadBancaria {
            get {
                return ResourceManager.GetString("objPluralEntidadBancaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partidas Presupuestales.
        /// </summary>
        public static string objPluralPartidaPresupuestal {
            get {
                return ResourceManager.GetString("objPluralPartidaPresupuestal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string objPluralRol {
            get {
                return ResourceManager.GetString("objPluralRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitudes Cotización.
        /// </summary>
        public static string objPluralSolicitudCotizacion {
            get {
                return ResourceManager.GetString("objPluralSolicitudCotizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle de Solicitudes Cotización Detalles.
        /// </summary>
        public static string objPluralSolicitudCotizacionDetalle {
            get {
                return ResourceManager.GetString("objPluralSolicitudCotizacionDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarjetas Empleado.
        /// </summary>
        public static string objPluralTarjetaEmpleado {
            get {
                return ResourceManager.GetString("objPluralTarjetaEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios.
        /// </summary>
        public static string objPluralUsuario {
            get {
                return ResourceManager.GetString("objPluralUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol.
        /// </summary>
        public static string objRol {
            get {
                return ResourceManager.GetString("objRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud Cotización.
        /// </summary>
        public static string objSolicitudCotizacion {
            get {
                return ResourceManager.GetString("objSolicitudCotizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle de Solicitud Cotización.
        /// </summary>
        public static string objSolicitudCotizacionDetalle {
            get {
                return ResourceManager.GetString("objSolicitudCotizacionDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarjeta Empleado.
        /// </summary>
        public static string objTarjetaEmpleado {
            get {
                return ResourceManager.GetString("objTarjetaEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string objUsuario {
            get {
                return ResourceManager.GetString("objUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar Contraseña.
        /// </summary>
        public static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendiente Cambio Contraseña.
        /// </summary>
        public static string PendienteCambio {
            get {
                return ResourceManager.GetString("PendienteCambio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurso.
        /// </summary>
        public static string Recurso {
            get {
                return ResourceManager.GetString("Recurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Evento.
        /// </summary>
        public static string TipoEvento {
            get {
                return ResourceManager.GetString("TipoEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor cambie su contraseña.
        /// </summary>
        public static string tituloCambiarPass {
            get {
                return ResourceManager.GetString("tituloCambiarPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Rol.
        /// </summary>
        public static string tituloCrearRol {
            get {
                return ResourceManager.GetString("tituloCrearRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Usuario.
        /// </summary>
        public static string tituloCrearUsuario {
            get {
                return ResourceManager.GetString("tituloCrearUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle Rol.
        /// </summary>
        public static string tituloDetalleRol {
            get {
                return ResourceManager.GetString("tituloDetalleRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle Usuario.
        /// </summary>
        public static string tituloDetalleUsuario {
            get {
                return ResourceManager.GetString("tituloDetalleUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Rol.
        /// </summary>
        public static string tituloEditarRol {
            get {
                return ResourceManager.GetString("tituloEditarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Usuario.
        /// </summary>
        public static string tituloEditarUsuario {
            get {
                return ResourceManager.GetString("tituloEditarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestión de Roles.
        /// </summary>
        public static string tituloRoles {
            get {
                return ResourceManager.GetString("tituloRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestión de Usuarios.
        /// </summary>
        public static string tituloUsuarios {
            get {
                return ResourceManager.GetString("tituloUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Método.
        /// </summary>
        public static string Trazador {
            get {
                return ResourceManager.GetString("Trazador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario Autorizador.
        /// </summary>
        public static string UsrAutorizador {
            get {
                return ResourceManager.GetString("UsrAutorizador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        public static string Valor {
            get {
                return ResourceManager.GetString("Valor", resourceCulture);
            }
        }
    }
}
