//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSWeb.Entidades.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MensajesValidaciones {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensajesValidaciones() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POSWeb.Entidades.ResourceFiles.MensajesValidaciones", typeof(MensajesValidaciones).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este Método no está permitido para este canal..
        /// </summary>
        public static string CanalNoPermiso {
            get {
                return ResourceManager.GetString("CanalNoPermiso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longitud mínima de la contraseña debe de ser al menos de: {0} caracteres..
        /// </summary>
        public static string PassMinCaracteres {
            get {
                return ResourceManager.GetString("PassMinCaracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña debe de contener al menos: {0} mayúscula.
        /// </summary>
        public static string PassMinMayusculas {
            get {
                return ResourceManager.GetString("PassMinMayusculas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña debe de contener al menos: {0} números..
        /// </summary>
        public static string PassMinNumeros {
            get {
                return ResourceManager.GetString("PassMinNumeros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña debe de contener al menos: {0} símbolo..
        /// </summary>
        public static string PassMinSimbolos {
            get {
                return ResourceManager.GetString("PassMinSimbolos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña no coincide, por favor ingresela de nuevo..
        /// </summary>
        public static string PassNoCoincide {
            get {
                return ResourceManager.GetString("PassNoCoincide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Código de la Moneda es requerido..
        /// </summary>
        public static string Req_CodigoMoneda {
            get {
                return ResourceManager.GetString("Req_CodigoMoneda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Codigo de Usuario es requerido..
        /// </summary>
        public static string Req_CodigoUsuario {
            get {
                return ResourceManager.GetString("Req_CodigoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Detalle del Lote es requerido..
        /// </summary>
        public static string Req_DetalleLote {
            get {
                return ResourceManager.GetString("Req_DetalleLote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El encargado de la Caja es requerido..
        /// </summary>
        public static string Req_EncargadoCaja {
            get {
                return ResourceManager.GetString("Req_EncargadoCaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdRubro es requerido..
        /// </summary>
        public static string Req_IdRubro {
            get {
                return ResourceManager.GetString("Req_IdRubro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En caso de Licitaciones, es requerido el campo IdLineaExt..
        /// </summary>
        public static string Req_LineaExterna {
            get {
                return ResourceManager.GetString("Req_LineaExterna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La moneda es requerida..
        /// </summary>
        public static string Req_Moneda {
            get {
                return ResourceManager.GetString("Req_Moneda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La moneda del limite de transacción es requerida..
        /// </summary>
        public static string Req_MonedaLimite {
            get {
                return ResourceManager.GetString("Req_MonedaLimite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de la Caja es requerido..
        /// </summary>
        public static string Req_NombreCaja {
            get {
                return ResourceManager.GetString("Req_NombreCaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre del catálogo es requerido..
        /// </summary>
        public static string Req_NombreCatalogo {
            get {
                return ResourceManager.GetString("Req_NombreCatalogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Token de Sesión es requerido.
        /// </summary>
        public static string Req_Token {
            get {
                return ResourceManager.GetString("Req_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario de creación es requerido..
        /// </summary>
        public static string Req_UsuarioCreacion {
            get {
                return ResourceManager.GetString("Req_UsuarioCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario de modificación es requerido..
        /// </summary>
        public static string Req_UsuarioModificacion {
            get {
                return ResourceManager.GetString("Req_UsuarioModificacion", resourceCulture);
            }
        }
    }
}
