//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSWeb.Entidades.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POSWeb.Entidades.ResourceFiles.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud Cotizacion aprobada correctamente..
        /// </summary>
        public static string bmAprobarSolicitudCotizacion {
            get {
                return ResourceManager.GetString("bmAprobarSolicitudCotizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerta configurada correctamente..
        /// </summary>
        public static string bmCreateAlertaEntidad {
            get {
                return ResourceManager.GetString("bmCreateAlertaEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorizacion agregado(a) correctamente..
        /// </summary>
        public static string bmCreateAutorizacion {
            get {
                return ResourceManager.GetString("bmCreateAutorizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutorizacionDetalle agregado(a) correctamente..
        /// </summary>
        public static string bmCreateAutorizacionDetalle {
            get {
                return ResourceManager.GetString("bmCreateAutorizacionDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Caja Chica ha sido creada exitosamente..
        /// </summary>
        public static string bmCreateCaja {
            get {
                return ResourceManager.GetString("bmCreateCaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canal agregado(a) correctamente. .
        /// </summary>
        public static string bmCreateCanal {
            get {
                return ResourceManager.GetString("bmCreateCanal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogo agregado(a) correctamente..
        /// </summary>
        public static string bmCreateCatalogo {
            get {
                return ResourceManager.GetString("bmCreateCatalogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta de Correo Electrónico agregada correctamente..
        /// </summary>
        public static string bmCreateCuentaEmail {
            get {
                return ResourceManager.GetString("bmCreateCuentaEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntidadBancaria agregado(a) correctamente..
        /// </summary>
        public static string bmCreateEntidadBancaria {
            get {
                return ResourceManager.GetString("bmCreateEntidadBancaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El lote ha sido creado exitosamente..
        /// </summary>
        public static string bmCreateLoteViatico {
            get {
                return ResourceManager.GetString("bmCreateLoteViatico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulo agregado(a) correctamente..
        /// </summary>
        public static string bmCreateModulo {
            get {
                return ResourceManager.GetString("bmCreateModulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneda creada exitosamente..
        /// </summary>
        public static string bmCreateMoneda {
            get {
                return ResourceManager.GetString("bmCreateMoneda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartidaPresupuestal agregado(a) correctamente. .
        /// </summary>
        public static string bmCreatePartidaPresupuestal {
            get {
                return ResourceManager.GetString("bmCreatePartidaPresupuestal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil agregado(a) correctamente..
        /// </summary>
        public static string bmCreatePerfil {
            get {
                return ResourceManager.GetString("bmCreatePerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol agregado(a) correctamente..
        /// </summary>
        public static string bmCreateRol {
            get {
                return ResourceManager.GetString("bmCreateRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sesion agregado(a) correctamente..
        /// </summary>
        public static string bmCreateSesion {
            get {
                return ResourceManager.GetString("bmCreateSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede procesar debido a que la solicitud no tiene detalle..
        /// </summary>
        public static string bmCreateSolicitudCotiDetalleNoCount {
            get {
                return ResourceManager.GetString("bmCreateSolicitudCotiDetalleNoCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SolicitudCotizacion agregado(a) correctamente..
        /// </summary>
        public static string bmCreateSolicitudCotizacion {
            get {
                return ResourceManager.GetString("bmCreateSolicitudCotizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud Cotizacion Detalle agregado(a) correctamente..
        /// </summary>
        public static string bmCreateSolicitudCotizacionDetalle {
            get {
                return ResourceManager.GetString("bmCreateSolicitudCotizacionDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TarjetaEmpleado agregado(a) correctamente..
        /// </summary>
        public static string bmCreateTarjetaEmpleado {
            get {
                return ResourceManager.GetString("bmCreateTarjetaEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo de Viático ha sido creado exitosamente..
        /// </summary>
        public static string bmCreateTipoViatico {
            get {
                return ResourceManager.GetString("bmCreateTipoViatico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario ha sido creado exitosamente..
        /// </summary>
        public static string bmCreateUsuario {
            get {
                return ResourceManager.GetString("bmCreateUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Vale ha sido creado exitosamente..
        /// </summary>
        public static string bmCreateVale {
            get {
                return ResourceManager.GetString("bmCreateVale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerta eliminada correctamente..
        /// </summary>
        public static string bmDeleteAlertaEntidad {
            get {
                return ResourceManager.GetString("bmDeleteAlertaEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Caja Chica ha sido eliminada exitosamente..
        /// </summary>
        public static string bmDeleteCaja {
            get {
                return ResourceManager.GetString("bmDeleteCaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canal eliminado(a) correctamente..
        /// </summary>
        public static string bmDeleteCanal {
            get {
                return ResourceManager.GetString("bmDeleteCanal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogo eliminado(a) correctamente..
        /// </summary>
        public static string bmDeleteCatalogo {
            get {
                return ResourceManager.GetString("bmDeleteCatalogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta de Correo Electrónico eliminada correctamente..
        /// </summary>
        public static string bmDeleteCuentaEmail {
            get {
                return ResourceManager.GetString("bmDeleteCuentaEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntidadBancaria eliminado(a) correctamente..
        /// </summary>
        public static string bmDeleteEntidadBancaria {
            get {
                return ResourceManager.GetString("bmDeleteEntidadBancaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El lote ha sido eliminado exitosamente..
        /// </summary>
        public static string bmDeleteLoteViatico {
            get {
                return ResourceManager.GetString("bmDeleteLoteViatico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulo eliminado(a) correctamente..
        /// </summary>
        public static string bmDeleteModulo {
            get {
                return ResourceManager.GetString("bmDeleteModulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneda eliminada exitosamente..
        /// </summary>
        public static string bmDeleteMoneda {
            get {
                return ResourceManager.GetString("bmDeleteMoneda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartidaPresupuestal eliminado(a) correctamente. .
        /// </summary>
        public static string bmDeletePartidaPresupuestal {
            get {
                return ResourceManager.GetString("bmDeletePartidaPresupuestal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil eliminado(a) correctamente..
        /// </summary>
        public static string bmDeletePerfil {
            get {
                return ResourceManager.GetString("bmDeletePerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol eliminado(a) correctamente..
        /// </summary>
        public static string bmDeleteRol {
            get {
                return ResourceManager.GetString("bmDeleteRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sesion eliminado(a) correctamente..
        /// </summary>
        public static string bmDeleteSesion {
            get {
                return ResourceManager.GetString("bmDeleteSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SolicitudCotizacion eliminado(a) correctamente..
        /// </summary>
        public static string bmDeleteSolicitudCotizacion {
            get {
                return ResourceManager.GetString("bmDeleteSolicitudCotizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud Cotizacion Detalle eliminado(a) correctamente..
        /// </summary>
        public static string bmDeleteSolicitudCotizacionDetalle {
            get {
                return ResourceManager.GetString("bmDeleteSolicitudCotizacionDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TarjetaEmpleado eliminado(a) correctamente..
        /// </summary>
        public static string bmDeleteTarjetaEmpleado {
            get {
                return ResourceManager.GetString("bmDeleteTarjetaEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo de Viático ha sido eliminado exitosamente..
        /// </summary>
        public static string bmDeleteTipoViatico {
            get {
                return ResourceManager.GetString("bmDeleteTipoViatico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario ha sido eliminado exitosamente..
        /// </summary>
        public static string bmDeleteUsuario {
            get {
                return ResourceManager.GetString("bmDeleteUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Vale ha sido eliminado exitosamente..
        /// </summary>
        public static string bmDeleteVale {
            get {
                return ResourceManager.GetString("bmDeleteVale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Vale ha sido desembolsado exitosamente..
        /// </summary>
        public static string bmDesembolsarVale {
            get {
                return ResourceManager.GetString("bmDesembolsarVale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerta modificada correctamente..
        /// </summary>
        public static string bmEditAlertaEntidad {
            get {
                return ResourceManager.GetString("bmEditAlertaEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Caja Chica ha sido editada exitosamente..
        /// </summary>
        public static string bmEditCaja {
            get {
                return ResourceManager.GetString("bmEditCaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canal modificado(a) correctamente..
        /// </summary>
        public static string bmEditCanal {
            get {
                return ResourceManager.GetString("bmEditCanal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogo modificado(a) correctamente..
        /// </summary>
        public static string bmEditCatalogo {
            get {
                return ResourceManager.GetString("bmEditCatalogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta de Correo Electrónico modificada correctamente..
        /// </summary>
        public static string bmEditCuentaEmail {
            get {
                return ResourceManager.GetString("bmEditCuentaEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntidadBancaria modificado(a) correctamente..
        /// </summary>
        public static string bmEditEntidadBancaria {
            get {
                return ResourceManager.GetString("bmEditEntidadBancaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El lote ha sido editado exitosamente..
        /// </summary>
        public static string bmEditLoteViatico {
            get {
                return ResourceManager.GetString("bmEditLoteViatico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulo modificado(a) correctamente..
        /// </summary>
        public static string bmEditModulo {
            get {
                return ResourceManager.GetString("bmEditModulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneda editada exitosamente..
        /// </summary>
        public static string bmEditMoneda {
            get {
                return ResourceManager.GetString("bmEditMoneda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartidaPresupuestal modificado(a) correctamente..
        /// </summary>
        public static string bmEditPartidaPresupuestal {
            get {
                return ResourceManager.GetString("bmEditPartidaPresupuestal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil modificado(a) correctamente..
        /// </summary>
        public static string bmEditPerfil {
            get {
                return ResourceManager.GetString("bmEditPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol modificado(a) correctamente..
        /// </summary>
        public static string bmEditRol {
            get {
                return ResourceManager.GetString("bmEditRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sesion modificado(a) correctamente..
        /// </summary>
        public static string bmEditSesion {
            get {
                return ResourceManager.GetString("bmEditSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SolicitudCotizacion modificado(a) correctamente..
        /// </summary>
        public static string bmEditSolicitudCotizacion {
            get {
                return ResourceManager.GetString("bmEditSolicitudCotizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud Cotizacion Detalle modificado(a) correctamente..
        /// </summary>
        public static string bmEditSolicitudCotizacionDetalle {
            get {
                return ResourceManager.GetString("bmEditSolicitudCotizacionDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TarjetaEmpleado modificado(a) correctamente..
        /// </summary>
        public static string bmEditTarjetaEmpleado {
            get {
                return ResourceManager.GetString("bmEditTarjetaEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo de Viático ha sido editado exitosamente..
        /// </summary>
        public static string bmEditTipoViatico {
            get {
                return ResourceManager.GetString("bmEditTipoViatico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario ha sido editado exitosamente..
        /// </summary>
        public static string bmEditUsuario {
            get {
                return ResourceManager.GetString("bmEditUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Vale ha sido editado exitosamente..
        /// </summary>
        public static string bmEditVale {
            get {
                return ResourceManager.GetString("bmEditVale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al procesar la transacción..
        /// </summary>
        public static string bmError {
            get {
                return ResourceManager.GetString("bmError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Vale ha sido liquidadp exitosamente..
        /// </summary>
        public static string bmLiquidarVale {
            get {
                return ResourceManager.GetString("bmLiquidarVale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operación no permitida..
        /// </summary>
        public static string bmNoPermitido {
            get {
                return ResourceManager.GetString("bmNoPermitido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha enviado correctamente el correo electrónico..
        /// </summary>
        public static string bmSendEmail {
            get {
                return ResourceManager.GetString("bmSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta acción no es reversible! ¿Desea eliminar?.
        /// </summary>
        public static string EliminarRegistro {
            get {
                return ResourceManager.GetString("EliminarRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta de correo funciona sin problemas..
        /// </summary>
        public static string msjCuentaCorreoBodyPrueba {
            get {
                return ResourceManager.GetString("msjCuentaCorreoBodyPrueba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esto es una prueba de correo.
        /// </summary>
        public static string msjCuentaCorreoSubjectPrueba {
            get {
                return ResourceManager.GetString("msjCuentaCorreoSubjectPrueba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error en el sistema, por favor contacte al administrador..
        /// </summary>
        public static string msjErrorGenerico {
            get {
                return ResourceManager.GetString("msjErrorGenerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su sesión ha expirado..
        /// </summary>
        public static string msjSesionExpiro {
            get {
                return ResourceManager.GetString("msjSesionExpiro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string tituloErrorSwAl {
            get {
                return ResourceManager.GetString("tituloErrorSwAl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consecutivo requerido.
        /// </summary>
        public static string vmRequeridoConsecutivoEntidad {
            get {
                return ResourceManager.GetString("vmRequeridoConsecutivoEntidad", resourceCulture);
            }
        }
    }
}
