//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSWeb.Entidades.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Respuestas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Respuestas() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POSWeb.Entidades.ResourceFiles.Respuestas", typeof(Respuestas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidad registrada con éxto.
        /// </summary>
        public static string E00 {
            get {
                return ResourceManager.GetString("E00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imposible eliminar.
        /// </summary>
        public static string GE01 {
            get {
                return ResourceManager.GetString("GE01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al guardar..
        /// </summary>
        public static string GI02 {
            get {
                return ResourceManager.GetString("GI02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La busqueda no obtuvo resultados..
        /// </summary>
        public static string GI03 {
            get {
                return ResourceManager.GetString("GI03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al realizar transacción.
        /// </summary>
        public static string GI04 {
            get {
                return ResourceManager.GetString("GI04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imposible Modificar.
        /// </summary>
        public static string GM01 {
            get {
                return ResourceManager.GetString("GM01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La transacción está fuera del horario permitido.
        /// </summary>
        public static string L01 {
            get {
                return ResourceManager.GetString("L01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horario no permitido para esta transacción..
        /// </summary>
        public static string L02 {
            get {
                return ResourceManager.GetString("L02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceso Realizado de manera exitosa.
        /// </summary>
        public static string PF00 {
            get {
                return ResourceManager.GetString("PF00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidad de Pago Favorito Invalida..
        /// </summary>
        public static string PF01 {
            get {
                return ResourceManager.GetString("PF01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro ingresado ya existe para la entidad, por favor ingresar otro..
        /// </summary>
        public static string S1001 {
            get {
                return ResourceManager.GetString("S1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario registrado con éxito..
        /// </summary>
        public static string U00 {
            get {
                return ResourceManager.GetString("U00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario inactivo..
        /// </summary>
        public static string U01 {
            get {
                return ResourceManager.GetString("U01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario bloqueado..
        /// </summary>
        public static string U02 {
            get {
                return ResourceManager.GetString("U02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario no existe..
        /// </summary>
        public static string U03 {
            get {
                return ResourceManager.GetString("U03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña está expirada..
        /// </summary>
        public static string U04 {
            get {
                return ResourceManager.GetString("U04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña es incorrecta..
        /// </summary>
        public static string U05 {
            get {
                return ResourceManager.GetString("U05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número de intentos ha alcanzado el límite. El usuario ha sido bloqueado..
        /// </summary>
        public static string U06 {
            get {
                return ResourceManager.GetString("U06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario tiene pendiente cambio de contraseña..
        /// </summary>
        public static string U07 {
            get {
                return ResourceManager.GetString("U07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código de usuario ya se encuentra registrado, por favor digite uno diferente..
        /// </summary>
        public static string U08 {
            get {
                return ResourceManager.GetString("U08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imposible validar contraseña..
        /// </summary>
        public static string U12 {
            get {
                return ResourceManager.GetString("U12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longitud mínima de la contraseña debe de ser al menos de: [vLongitud] ..
        /// </summary>
        public static string Ux04 {
            get {
                return ResourceManager.GetString("Ux04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña debe de contener al menos: [vCont] números..
        /// </summary>
        public static string Ux05 {
            get {
                return ResourceManager.GetString("Ux05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña debe de contener al menos: [vCont] mayusculas..
        /// </summary>
        public static string Ux06 {
            get {
                return ResourceManager.GetString("Ux06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña debe de contener al menos: [vCont] simbolos..
        /// </summary>
        public static string Ux07 {
            get {
                return ResourceManager.GetString("Ux07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña no puede ser igual a las últimas [vCont] contraseñas..
        /// </summary>
        public static string Ux08 {
            get {
                return ResourceManager.GetString("Ux08", resourceCulture);
            }
        }
    }
}
